default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_new_development

test:
  <<: *default
  database: blog_new_test

production:
  <<: *default
  database: blog_new_production
  username: blog_demo
  password: <%= ENV["BLOG_DEMO_DATABASE_PASSWORD"] %>
